name: Deploy Virtual Machine Bicep
on: [push]
jobs:
  deploy-bicep:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: 1dad7d18-a6d1-40c2-a56f-7dfe89999e67
        resourceGroupName: actions-virtual-machine
        template: ./virtualMachine.bicep
        parameters: 'adminPassword=${{ secrets.VM_PASSWORD }}'
        failOnStdErr: false
